version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb-container
    env_file:
      - .env
    volumes:
      - mariadb_data:/home/tlam/data/mariadb
    ports:
      - "3306:3306"
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx-container
    env_file:
      - .env
    volumes:
      - wordpress_data:/home/tlam/data/wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-container
    env_file:
      - .env
    volumes:
      - wordpress_data:/home/tlam/data/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
    networks:
      - inception_network

volumes:
  mariadb_data:
  wordpress_data:

  networks:
    inception_network:
      driver: bridge